#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Scrape2Feed;
use feature qw (say );
use lib qw (/home/toshi/perl/lib );
use HashDump;
use YAML;

my $setting = 'shihoujournal';

my $site = Scrape2Feed->new('site_name' => $setting);

my $list = $site->get_list(1,2);

HashDump->load($list);


#my $contents = $site->get_contents();
#my $config = $gunosy->config();

#HashDump->load($config);
#HashDump->load($contents);






