--- 
'gunosy.com':
  "type": 'flat'
  "site_title": '//head/title'
  "site_url": 'http://gunosy.com/toshi0104'
  "next_page": '//nav[@class="navigation"]//a'
  "container": '//div[@class="entry-content"]'
  "entry_title": '//h1'
  "entry_date": 
  "entry_permalink": '//a'
  "entry_content": '//div[@class="entry-summary"]'
'gunosy.com.japannewsfeeds':
  "type": 'flat'
  "site_title": '//head/title'
  "site_url": 'http://gunosy.com/JapanNewsFeeds'
  "next_page": '//nav[@class="navigation"]//a'
  "container": '//div[@class="entry-content"]'
  "entry_title": '//h1'
  "entry_date": 
  "entry_permalink": '//a'
  "entry_content": '//div[@class="entry-summary"]'
'twitter.com':
  "type": 'flat'
  "site_title": '//head/title' 
  "site_url": 'https://m.twitter.com/'
  "next_page": '//div[@class="w-button-more"]/a'
  "container": '//table[@class="tweet"]'
  "entry_title": '//strong[@class="fullname"]'
  "entry_date": 
  "entry_permalink": '//span[@class="metadata"]/a'
  "entry_content": '//div[@class="tweet-text"]'
'shihoujournal':
  "type": 'index'
  "site_title": '//head/title'
  "site_url": 'http://www.shihoujournal.co.jp/news/index.html'
  "next_page": '//table[last()-1]/tr/td/a'
  "index": '//table[position()<last()-1]'
  "index_entry_title": '//dd'
  "index_entry_permalink": '//a'
  "entry_date": 
  "entry_content": '//div[@class="article"]'
'journal':
  "type": 'index'
  "site_title": '//head/title'
  "site_url": 'http://www.the-journal.jp/'
  "next_page": 
  "index": '//p/a[position()+1<last()-1]'
  "index_entry_title": '.'
  "index_entry_permalink": '.'
  "entry_date": '//span[@class="post-footers"]'
  "entry_content": '//div[@class="entry-content"]'

