#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Scrape2Feed;
use feature qw (say );
use lib qw (/home/toshi/perl/lib );
use Encode 'encode_utf8';
use HashDump;
use HTML::Entities;
use WWW::Mechanize;

my $username = 'toshi0104';
my $password = 'xxxxxxxx';

my $login_url = 'https://mobile.twitter.com/session/new';
my $target_url = 'https://mobile.twitter.com/toshi0104';


my $twitter = Scrape2Feed->new('site_name' => 'twitter.com');
my $login_opt = { 
	'login_url' => $login_url,
	'fields' => {
		'username' => $username,
		'password' => $password,
	},
};								
$twitter->login($login_opt);
$twitter->url($target_url);

my $content = $twitter->get_contents(1,3);

HashDump->load($content);







