#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Scrape2Feed;
use feature qw (say );
use lib qw (/home/toshi/perl/lib );
use HashDump;
use URI::Escape;
use YAML; 
use Encode 'encode_utf8'; 


my $query = '尖閣';
my $username = 'toshi0104';
my $password = 'xxxxxxxxx';
my $loginurl = 'https://mobile.twitter.com/session/new';
my $login_opt = {
	'login_url' => $loginurl,
	'fields' => {
		'username' => $username,
		'password' => $password,
	},
};

my $contents = Scrape2Feed->new('site_name' => 'twitter.com');
$contents->login($login_opt);

my $enc_query = uri_escape_utf8( $query);
my $url = 'https://mobile.twitter.com/search?q=' . $enc_query .'&x=24&y=11';

say 'query = ' . $query;
say 'search url =' . $url;

$contents->url($url);
$contents->rss_ver( '2.0');

my $res = $contents->get_rss(1,5);
my $output_file_name = $query . '.result';

open my $fh, '>', $output_file_name;
print $fh encode_utf8(Dump($res));


