#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Scrape2Feed;
use feature qw (say );
use lib qw (/home/toshi/perl/lib );
use Encode 'encode_utf8';
use HashDump;
use HTML::Entities;

my $twitter = Scrape2Feed->new('site_name' => 'twitter.com');

my $url = 'https://mobile.twitter.com/search?q=%E5%A4%A7%E9%98%AA&x=24&y=11';
$twitter->url($url);

my $list = $twitter->get_contents(1,3);
my $rss = $twitter->get_rss();

my $file = '/home/toshi/WWW/tmp/tmp.rss';

open my $fh, '>', $file or die ;

#print $fh decode_entities($rss->as_string);

print $fh $rss->as_string;

#HashDump->load($rss);







