#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use Scrape2Feed;
use feature qw (say );
use lib qw (/home/toshi/perl/lib );
use HashDump;

my $twitter = Scrape2Feed->new('site_name' => 'twitter.com');

my $url = 'https://mobile.twitter.com/search?q=%E5%A4%A7%E9%98%AA&x=24&y=11';
$twitter->url($url);

my $list = $twitter->get_contents(1,3);

HashDump->load($list);







